PUT http://localhost:5005/users/3
Content-Type: application/json

{
    "fname": "jack",
    "lname": "man",
    "username": "jackman",
    "email": "jackman@email.com"
}

###

POST http://localhost:5005/auth/login
Content-Type: application/json

{
    "username": "inmanjlai",
    "hashed_password": "ww"
}